apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: ovpn-controller-rolebinding
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: ovpn-editor-role
subjects:
  - kind: ServiceAccount
    name: ovpn-manager
    namespace: system
