# permissions for end users to view serviceexportconfigs.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: serviceexportconfig-viewer-role
rules:
  - apiGroups:
      - controller.kubeslice.io
    resources:
      - serviceexportconfigs
    verbs:
      - get
      - list
      - watch
  - apiGroups:
      - controller.kubeslice.io
    resources:
      - serviceexportconfigs/status
    verbs:
      - get
