# permissions for end users to view sliceconfigs.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: sliceconfig-viewer-role
rules:
  - apiGroups:
      - controller.kubeslice.io
    resources:
      - sliceconfigs
    verbs:
      - get
      - list
      - watch
  - apiGroups:
      - controller.kubeslice.io
    resources:
      - sliceconfigs/status
    verbs:
      - get
