# permissions for end users to edit workersliceconfigs.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: workersliceconfig-editor-role
rules:
  - apiGroups:
      - worker.kubeslice.io
    resources:
      - workersliceconfigs
    verbs:
      - create
      - delete
      - get
      - list
      - patch
      - update
      - watch
  - apiGroups:
      - worker.kubeslice.io
    resources:
      - workersliceconfigs/status
    verbs:
      - get
