# permissions for end users to view workerserviceimports.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: workerserviceimport-viewer-role
rules:
  - apiGroups:
      - worker.kubeslice.io
    resources:
      - workerserviceimports
    verbs:
      - get
      - list
      - watch
  - apiGroups:
      - worker.kubeslice.io
    resources:
      - workerserviceimports/status
    verbs:
      - get
