# permissions for end users to edit workerslicegateways.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: workerslicegateway-editor-role
rules:
  - apiGroups:
      - worker.kubeslice.io
    resources:
      - workerslicegateways
    verbs:
      - create
      - delete
      - get
      - list
      - patch
      - update
      - watch
  - apiGroups:
      - worker.kubeslice.io
    resources:
      - workerslicegateways/status
    verbs:
      - get
