# permissions for end users to edit workerserviceimports.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: workerserviceimport-editor-role
rules:
  - apiGroups:
      - worker.kubeslice.io
    resources:
      - workerserviceimports
    verbs:
      - create
      - delete
      - get
      - list
      - patch
      - update
      - watch
  - apiGroups:
      - worker.kubeslice.io
    resources:
      - workerserviceimports/status
    verbs:
      - get
