# permissions for end users to view workersliceconfigs.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: workersliceconfig-viewer-role
rules:
  - apiGroups:
      - worker.kubeslice.io
    resources:
      - workersliceconfigs
    verbs:
      - get
      - list
      - watch
  - apiGroups:
      - worker.kubeslice.io
    resources:
      - workersliceconfigs/status
    verbs:
      - get
