apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  labels:
    kubeslice-resource-owner: controller
  name: kubeslice-role
rules:
  - verbs:
      - "*"
    apiGroups:
      - "*"
    resources:
      - "*"